// USERS
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// DATA
export const SET_SCREAMS = "SET_SCREAMS";
export const LOADING_DATA = "LOADING_DATA";
export const POST_SCREAM = "POST_SCREAM";

// UI
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
